### ISSUE TITLE
Call out response data for Facial Detection events

### ISSUE THREAD

**Issue by HolyChris** [MistyCommunity/Documentation#1]
I just learned there is a 'distance' field that is a part of the reponse from a successful facial detection event that is the estimated distance in meters from the robot that the face was seen. 

This is based on an average face size and is a loose approximation of distance. We should call out all the available response data that comes back from the robot.

**Comment by johnathanDOS** [comment]
Looks like this can be closed. Unsure when it was added but the `distance` field is documented for the `ComputerVision` data packet sent for face detection events. See https://docs.mistyrobotics.com/docs/reference/sensor-data/#computervision-beta-
