### ISSUE TITLE
APIXU no longer exists

### ISSUE THREAD

**Issue by cbattlegear** [MistyCommunity/Documentation#104]
APIXU was shut down as of 10/14/2019 and updated to weatherstack. APIXU is currently referenced as part of the external request example: https://docs.mistyrobotics.com/misty-ii/coding-misty/javascript-sdk-tutorials/#external-requests

**Comment by johnathanDOS** [comment]
Thanks for calling this out, @cbattlegear! We'll review this within the next few days and I'll let you know here when it's been updated. Appreciate you taking the time to file an issue here :)

**Comment by johnathanDOS** [comment]
@cbattlegear -- In a [recent PR](https://github.com/MistyCommunity/Documentation/pull/108) we updated the docs to use the Weatherstack API in the external request [code sample](https://docs.mistyrobotics.com/misty-ii/coding-misty/javascript-sdk-code-samples/#externalrequest_getdata) and [tutorial](https://docs.mistyrobotics.com/misty-ii/coding-misty/javascript-sdk-tutorials/#external-requests), and replaced references to APIXU elsewhere in the docs. I'm going to close this
