### ISSUE TITLE
URL Typo in system-updates.md

### ISSUE THREAD

**Issue by mbdmbd** [MistyCommunity/Documentation#117]
https://github.com/MistyCommunity/Documentation/blob/master/src/content/misty-ii/robot/system-updates.md

Has:
`You can check the software versions on your Misty by sending a request to the endpoint for the [`GetDeviceInformation`](../../..//misty-ii/reference/rest/#getdeviceinformation) command. Look for the values of the following properties in the JSON object that Misty returns:`

It should be:

`You can check the software versions on your Misty by sending a request to the endpoint for the [`GetDeviceInformation`](../../../misty-ii/reference/rest/#getdeviceinformation) command. Look for the values of the following properties in the JSON object that Misty returns:`

The extra slash sends people to a page not found at https://docs.mistyrobotics.com/misty-ii/robot/system-updates/

**Comment by johnathanDOS** [comment]
@mbdmbd strikes again! Thanks for the great feedback. We just deployed a fix, and that URL should be in working order (may require a refresh :) )
