### ISSUE TITLE
broken URL in README

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Documentation#23]
## Summary
[in the README](https://github.com/MistyCommunity/Documentation/blob/24ae35cca44fe0999199be4e5c4a50aa805b19c7/README.md), `docs.mistyrobotics.com` is automatically treated as a URL, but the result is broken.

## Proposed solution
write the full URL, e.g., https://docs.mistyrobotics.com/

**Comment by johnathanDOS** [comment]
Thanks @slivingston! Fixed here: 5a55feedbcbf39d0f8955047b5d984c798a0eebd
