### ISSUE TITLE
another broken URL in README

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Documentation#24]
## Summary

[in the README](https://github.com/MistyCommunity/Documentation/blob/5a55feedbcbf39d0f8955047b5d984c798a0eebd/README.md), `docs.particle.io` is automatically treated as a URL, but the result is broken.

## Proposed solution

write the full URL, e.g., https://docs.particle.io/

## Related issuse

#23 
(next time I will be more careful to collect these all into a single issue.)

**Comment by johnathanDOS** [comment]
Thanks @slivingston. I should've checked the rest of the URLs in the README when you opened the initial issue 🙂 

Fixed here: https://github.com/MistyCommunity/Documentation/commit/ba2ff646d3518963c19e9024cc0ebe17e56a3a65
