### ISSUE TITLE
infinitely recursing links

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Documentation#33]
## Summary and proposed solution

I have an old URL into the REST API documentation that is no longer valid: https://docs.mistyrobotics.com/apis/api-reference/rest/#changedisplayimage

The new "Misty Docs" page is shown without changing the URL in the navigator. This leads to broken relative links in the page.

This error matters because old URLs might still be out there on the Web, so you should indicate via HTTP that the page moved. E.g., return 301 and the new URL. I understand if you think that it is not worth the effort to define a redirect rule for every old URL. In that case, at least provide a catch-all redirect to the new "Misty Docs" homepage, which will yield a correct URL in the user's navigator.

## Example
Visit <https://docs.mistyrobotics.com/apis/api-reference/rest/#changedisplayimage>, then try to follow the links "On-Robot JavaScript API Architecture" or "REST API & WebSocket Architecture". You should arrive at the same page but with parts added to the URL path. Following the links again leads to more parts added to the URL while arriving back at the same page.

**Comment by johnathanDOS** [comment]
Thanks for catching this, @slivingston. With Misty and the developer tools in their alpha state, I'm anticipating more changes to the architecture of the docs site in the future. It's unlikely we have the resources to maintain redirect rules for specific URLs each time they change; I'll look at implementing a catch-all redirect to prevent the infinitely recursing links bug you've noted here.

**Comment by johnathanDOS** [comment]
@slivingston I've instantiated a redirect rule that sends requests for non-existing objects to https://docs.mistyrobotics.com. This rule does not remove the anchor link (/#changedisplayimage in your example) from the URL, but the anchor link does not append to the URL when you try to follow a link to another part of the docs from the home page.

I'm going to close this issue. Please test this out, and re-open the issue if our solution does not meet your requirements. Thanks very much for noticing this and calling our attention to it!
