### ISSUE TITLE
halt command?

### ISSUE THREAD

**Issue by slivingston** [MistyCommunity/Documentation#57]
Should it be `POST /api/halt`, not `POST /api/robot/halt` that is written at https://github.com/MistyCommunity/Documentation/blob/15e5b5fc86450fb13f0b32542f2822b840e2bec1/src/content/docs/reference/rest.md#halt (and as released at <https://docs.mistyrobotics.com/docs/reference/rest/#halt>)?

I have an FEP robot, and the response to `POST /api/robot/halt` is

    {"error":"'/robot/halt' command not found for post request","status":"Failed"}

whereas `POST /api/halt` succeeds.

**Comment by johnathanDOS** [comment]
@slivingston You're correct -- that's a bug with the docs site. Looks like we overlooked this with a recent endpoint update. The endpoint has been updated to `POST /api/halt`: 0589d847df3801b61695b7058be5b0abba8b2d76. You may need to perform a hard refresh of the URL https://docs.mistyrobotics.com/docs/reference/rest/#halt to see these changes right away. Thanks for catching this!
