### ISSUE TITLE
MistyVoice needs some attention

### ISSUE THREAD

**Issue by HolyChris** [MistyCommunity/Documentation#9]
The 'Misty Voice' link referenced is in need of some updating (Currently does not work)

https://github.com/MistyCommunity/MistyI/tree/master/API_Wrappers/Python/samples/mistyvoice

**Comment by slivingston** [comment]
should this issue be closed?

the given URL is no longer active. I searched for `mistyvoice` but only found https://github.com/MistyCommunity/SampleCode/commit/af32f6a1fc3237e9524f0a442f0e6d7b3752bfe7

**Comment by johnathanDOS** [comment]
I'm closing this issue for now; the MistyVoice sample referenced [here](https://github.com/MistyCommunity/Documentation/issues/9#issue-379469704) appears to have been moved out of the MistyCommunity GitHub org.
